### ISSUE TITLE
Crash from pyedbglib at startup

### ISSUE THREAD

**Issue by Jacajack** [stemnic/pyAVRdbg#13]
Hi,

I installed `pymcuprog` and the updated dependency list (as in #7). However, regardless of the device I choose, when I run the main file, I get the following error:

```
$ python3 main.py 
ERROR:pyedbglib.hidtransport.hidtransportbase:No CMSIS-DAP devices found.
INFO:pymcuprog.deviceinfo.deviceinfo:Looking for device avr128da48
Traceback (most recent call last):
  File "/home/j/Desktop/pyAVRdbg/main.py", line 15, in <module>
    dbg = debugger.Debugger("avr128da48")
  File "/home/j/Desktop/pyAVRdbg/debugger.py", line 35, in __init__
    self.housekeeper = housekeepingprotocol.Jtagice3HousekeepingProtocol(self.transport)
  File "/home/j/.local/lib/python3.10/site-packages/pyedbglib/protocols/housekeepingprotocol.py", line 76, in __init__
    super(Jtagice3HousekeepingProtocol, self).__init__(transport, Jtagice3Protocol.HANDLER_HOUSEKEEPING)
  File "/home/j/.local/lib/python3.10/site-packages/pyedbglib/protocols/jtagice3protocol.py", line 163, in __init__
    super(Jtagice3Protocol, self).__init__(transport, handler)
  File "/home/j/.local/lib/python3.10/site-packages/pyedbglib/protocols/jtagice3protocol.py", line 48, in __init__
    super(Jtagice3Command, self).__init__(transport)
  File "/home/j/.local/lib/python3.10/site-packages/pyedbglib/protocols/avrcmsisdap.py", line 39, in __init__
    self.ep_size = transport.get_report_size()
  File "/home/j/.local/lib/python3.10/site-packages/pyedbglib/hidtransport/hidtransportbase.py", line 165, in get_report_size
    return self.device.packet_size
AttributeError: 'NoneType' object has no attribute 'packet_size'
```

Do you have any idea what might cause that? Thanks a lot!

**Comment by stemnic** [comment]
From an initial glance it looks like you might not have a device connected which is defined on main.py line 15.

What device are you trying to use it with? :)

**Comment by mraardvark** [comment]
"No CMSIS-DAP devices found"
I think "devices" means "debuggers" - which debugger are you using?

**Comment by Jacajack** [comment]
@stemnic At first I tried with `avr128db32` (it's not in the readme, but it seems to be supported by pymcuprog?). It didn't work, so I started experimenting with different devices mentioned in the readme, but with no success.

@mraardvark Oh, so this may be a misunderstanding on my part. I only had a USB/UART converter connected as a UPDI programmer. I thought that would be sufficient for debugging. Do I need any additional hardware in order to use this tool?

**Comment by stemnic** [comment]
For this to work you need to have a usb avr debugger connected that supports CMSIS-DAP. Which then speaks to the device over UPDI. AFAIK there is no public way to debug directly over updi without such a debugger, but @mraardvark can correct me if I am wrong here. Some dev boards have such a debugger on them like the Curiosity-Nano line. External debuggers are products like the atmel ICE

But you are correct as you stated that you can program the avr over updi just with a serial port https://github.com/mraardvark/pyupdi

**Comment by mraardvark** [comment]
Correct. Use pymcuprog with -t uart to program over serial

**Comment by Jacajack** [comment]
I'm using avrdude 7.0 for programming and it works very well with UPDI. I was just living under the illusion that we've finally reached the days when debugging AVR didn't require any additional hardware thanks to UPDI :)

I guess I'll look around for a debugger kit then. Thank you both for your time and tips
