### ISSUE TITLE
platformio?

### ISSUE THREAD

**Issue by mraardvark** [stemnic/pyAVRdbg#6]
Greetings, old friend :)
Any interest in taking this further, for example integration into platformio?

**Comment by stemnic** [comment]
Hi there :)

That would be intresteing🤔, though I have not any experience with using platformio with vscode.

I would imagen it should be relative simple to implement if you base it upon prosjects if I read the documentation correctly
https://docs.platformio.org/en/latest/projectconf/section_env_debug.html

As long as you can run a python file and then start gdb for remote debugging it should work just fine

There are however still some cleanup though which the codebase needs to make it into a "usable" program for people other than a hacky example. Thats on my todo list when I get the time :)

**Comment by mraardvark** [comment]
Ah, actually I did manage to get it to work from platformio... so we are heading in the right direction there at least.
FYI - I plan to "take in" the debugger layer (extension of avr8 protocol really) into pymcuprog - of course that will be cleaned somewhat along the way.
The GDB server could be al alternative CLI in pymcuprog as well, but might be better off as a separate package entirely...

**Comment by stemnic** [comment]
That would be nice to have it as a extension of the avr8 protocol, it would then be convinient to have better event handling [example](https://github.com/stemnic/pyAVRdbg/blob/36194d5dff884cfb8e9629e9ed329b3687fb7a3a/debugger.py#L44-L76). 

I think it's "most clean" to seperate the GDB(rsp) server into a seperate python package which would depend of edbglib or pymcuprog depending on how you would go about implemnting the debugging layer.

In practice the GDB server is only a tcp server which can parse the different rsp commands which is ascii encoded. The only hard part there is to make it compatible with the assumtions gdb has taken with the avr architecture
