### ISSUE TITLE
Applicability for Arduino Nano Every board

### ISSUE THREAD

**Issue by maxgerhardt** [stemnic/pyAVRdbg#8]
I'm looking for a solution on how to get a GDB server working that works on the Arduino Nano Every board. The board has a ATMega4809 chip and a SAMD11 chip for handling USB-Serial and programming. 

Flashing works normally in the Arduino IDE or PlatformIO with avrdude with commands like 

>avrdude -v -p atmega4809 -C "C:\Users\Max\.platformio\packages\tool-avrdude-megaavr\avrdude.conf" -c jtag2updi -Ufuse2:w:0x01:m -Ufuse5:w:0xC9:m -Ufuse8:w:0x00:m -Ulock:w:0xc5:m -b 115200 -V -e -D -P "COM20" -U flash:w:.pio\build\nano_every\firmware.hex:i

So the `-c jtag2updi` protocol works on a serial port in my case. 

So I though the program in this repo might give me a GDB server for this microcontroller which is connected via UPDI to the SAMD11 chip and exposes a serial port which works with avrdude apparently. But installing and starting the program just gives me a 

>C:\Users\Max\pyAVRdbg>python main.py
ERROR:pyedbglib.hidtransport.hidtransportbase:No CMSIS-DAP devices found.
INFO:pymcuprog.deviceinfo.deviceinfo:Looking for device atmega4809

Well the programmer is no CMSIS-DAP device though. 

Am I configuring this program wrongly or is this not supported / intended to open a GDB server over that device?

**Comment by mraardvark** [comment]
Arduino uses the D11 solution on that board as a programming bridge, and it does not have debugging capability.
The solution here interfaces with a nEDBG / EDBG / Atmelice etc which provides the debug functionality.

**Comment by maxgerhardt** [comment]
Hm I see. I have 10000 foot view on this topic at this point -- thought if AVRDude was able to use serial interface to program the chip via UPDI, it would also be general enough to use the other UPDI features for debugging. 

Then I seem better of at https://github.com/Florin-Popescu/avarice for this case -- if I'm not mistaken again 😅.

**Comment by mraardvark** [comment]
Not convinced either - the two boards listed there contain full debuggers too...

**Comment by maxgerhardt** [comment]
Hmm :/ 

I'll see what the author answers to my issue but if that's the case then I guess I have to reprogramm the SAMD11 chip with my own firmware (thankfully [reprogramming is possible](https://www.arduino.cc/en/Guide/NANOEvery#firmware-for-samd11d14a), with the firmware possibly based on https://github.com/ElTangas/jtag2updi maybe) and extend avarice to work with that device.. somhow.. 

I mean on the other side avarice explicitly supports the `  -2, --mkII                  Connect to JTAG ICE mkII` option which is the kind of device / protocol that avrdude uses, so maybe it works out after all. 

``` 
         Using Port                    : COM20
         Using Programmer              : jtag2updi
         Overriding Baud Rate          : 115200
..
JTAG ICE mkII sign-on message:
Communications protocol version: 1
M_MCU:
  boot-loader FW version:        1
  firmware version:              6.00
  hardware version:              1
S_MCU:
  boot-loader FW version:        1
  firmware version:              6.00
  hardware version:              1
Serial number:                   00:00:00:00:00:00
Device ID:                       JTAGICE mkII
         AVR Part                      : ATmega4809
..
```

**Comment by mraardvark** [comment]
OK - good luck!

**Comment by jaykoby** [comment]
Hi @maxgerhardt ,

how far did you come with your plan of a GDB server working on the Arduino Nano Every board? 

I've been looking for a solution to debug arduino boards (for example the Arduino Leonardo / Nano Every) cheaply (for teaching context) for an eternity now. Maybe you have made some progress in your venture, which you would like to share with us? :-)

I actually come from the field of STM32 Cortex processors and always thought that there MUST also be a low cost, open source way to debug AVR ATmegas on-chip.... :-(

**Comment by maxgerhardt** [comment]
I did not further modify this program, but after a lot of hacking around (debug probe firmware on a Arduino Micro, custom platformio.ini), we managed to achieve debugging. See https://community.platformio.org/t/debug-an-avr-4809-with-microupdi/19926/41?u=maxgerhardt. This is not yet at all integrated in PlatformIO, and I'm not currently working on this.
